Adjust the date math in generateQuarterForms.js
Enterprise-CMCS/macpro-mdct-seds pull request #9212
Opened 2023-04-18 22:02 UTC by benmartin-coforma

### Description
When generateQuarterForms is called automatically on the first day of each quarter, it must generate forms for the _previous_ three months. This PR fixes an off-by-one error in that calculation.

### Related ticket(s)
MDCT-2180

---
### How to test
Wait until July 1st and see what happens? I isolated the math into a function, and tested that function locally with this suite. I didn't commit these tests today; I think setting up unit testing for SEDS would be out-of-scope for this ticket.

![image](https://user-images.githubusercontent.com/126210497/232914477-29361ed5-17f0-4f05-adec-c94584b5df4b.png)

### Important updates
n/a

---
### Author checklist
- [x] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [x] I have updated relevant documentation, if necessary

2023-04-19 15:50 UTC, benmartin-coforma commented
For the record, here are those tests copy-pastable:
```js
const testCases = [
  { inputDate: new Date("2022-10-01 00:00"), expectedQuarter: { year: 2022, quarter: 4 } },
  { inputDate: new Date("2022-12-31 23:59"), expectedQuarter: { year: 2022, quarter: 4 } },
  { inputDate: new Date("2023-01-01 00:00"), expectedQuarter: { year: 2023, quarter: 1 } },
  { inputDate: new Date("2023-02-01 00:00"), expectedQuarter: { year: 2023, quarter: 1 } },
  { inputDate: new Date("2023-03-01 00:00"), expectedQuarter: { year: 2023, quarter: 1 } },
  { inputDate: new Date("2023-03-31 23:59"), expectedQuarter: { year: 2023, quarter: 1 } },
  { inputDate: new Date("2023-04-01 00:00"), expectedQuarter: { year: 2023, quarter: 2 } },
];

let failureCount = 0;
for (let { inputDate, expectedQuarter } of testCases) {
  let calculatedQuarter = calculateFormQuarterFromDate(inputDate);
  let pass = expectedQuarter.year === calculatedQuarter.year
          && expectedQuarter.month === calculatedQuarter.month;
  if (pass) {
    console.log(`✅ ${inputDate} --> ${expectedQuarter.year} Q${expectedQuarter.quarter}`);
  } else {
    failureCount += 1;
    console.error(`❌ ${inputDate} --> ${calculatedQuarter.year} Q${calculatedQuarter.quarter} (Expected ${expectedQuarter.year} Q${expectedQuarter.quarter})`);
  }
}

if (failureCount === 0) {
  console.log("All tests pass!");
} else {
  console.error(`${failureCount} tests failed`);
}
```

2023-04-19 17:00 UTC, BearHanded requested changes

2023-04-19 17:02 UTC, benmartin-coforma commented on services/app-api/handlers/forms/post/generateQuarterForms.js
> +  let quarter = month % 3 + 1;
Definitely!

2023-04-19 19:04 UTC, BearHanded approved these changes

2023-04-24 19:18 UTC, ntsummers1 approved these changes

2023-04-24 19:22 UTC, merged